version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: playground_app
      MYSQL_USER: playground_user
      MYSQL_PASSWORD: playground_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: app-container
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: playground_user
      DB_PASSWORD: playground_password
      DB_DATABASE: playground_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db_data:
